sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
after_success:
- ./gradlew jacocoTestReport coveralls
- ./scripts/deploy.sh
addons:
  apt:
    packages:
    - sshpass
notifications:
  slack:
    secure: s1gWwpjKHJ0jXuGtZvHrC5PKfXKsI6wdpZpxhrfpN1XJOoHpHFH/4iTYpADSTr8MQdI3vpwOH5Xk3P78QXtwkU9dYbPAenGVomXLa8eIkPfi/I0VkdwL4FszfXYgbel8BZzSeEG26GZr40bSTlZB4FAK0c/OAzmZVN5kdWwmsZMxvq53y4DUctXpw8Fi9maBltIkSi2kJgaMNGQBPiuOiDVrksxg9aFWGVVG2JfQQ1NJCXS91UvKEUOuY+ZK4C/D8yWogXi8HvwqRAdWGpW7a7PWCtbxofcb9st/w746tD5wvJc8jVT5B/p9D+0J/5CsSw+7yt3/5py8SifFU0/bDu8wxUCg+5UGvDeF4hH8If63gRwpsFCBtSnqT2DovufyBCOGDGR35x3fvUyxxVaraylNAgf/YWMTuZhBI415NZko9u0COEMWxliYUGi8uVIjkwRpjIVzYEIw+omGql9nWEtVug/xx11JXJ7LjG3PpcnBNB5JbJe+EjrbdybXcEeZFpKhRKGqaVW52RhJTdE5rVP3i/Bok8fiTk8T6ljCG9DJV0/4ZEkLPezA96wac1T/3f8PkYWSohKDG0NSf2V9WSpmYJxNr0wFqlf4KBQPLf0nY0M8sP827zBuND09Pg+nnu0i84FBx4/TdR7Sxe5lnqbND4/YKIQykZ8e+lLIbrc=
