tmc:
  sandboxUrl: http://localhost:3001
  notifyUrl: http://localhost:1337/submission-result

security:
  oauth2:
    client:
      tmc:
        redirectUri: http://localhost:8080/oauth2/authorize/code/tmc
